version 0.1-6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24,7 +24,7 @@ if ! [ -z "$USESPECIALPYTHONVERSION" ]; then
 fi 
 
 PYVERSION=`python -c "import sys;import distutils.sysconfig as sc;sys.stdout.write(sc.get_config_var('VERSION'))"`
-PYINCLUDE=`python -c "import sys;import distutils.sysconfig as sc;sys.stdout.write(sc.get_config_var('INCLUDEPY'))"`
+## PYINCLUDE=`python -c "import sys;import distutils.sysconfig as sc;sys.stdout.write(sc.get_config_var('INCLUDEPY'))"`
 PYBINPATH=`python -c "import sys;import os;sys.stdout.write(os.path.dirname(sys.executable))"`
 # sys.version_info.major would be a alternative to hexversion
 PY3FLAG=`python -c 'import sys; print("%i" % (sys.hexversion<0x03000000))'`
@@ -36,16 +36,23 @@ PICFLAGS=`"${R_HOME}/bin/R" CMD config CXX11PICFLAGS`
 ## echo $PICFLAGS
 ## echo ""
 
+## TODO: 
+## Change the generation of PKG_LIBS so it works with coda.
+## PYLIBS="PKG_LIBS="`python -c 'import sysconfig; print(" ".join(sysconfig.get_config_var("LDSHARED").split()[1:]))'`
 if [ $PY3FLAG -eq 0 ]; then
     echo "python version is > 3"
-    PYXY="PYTHONLIBXY=libpython"$PYVERSION"m.so"
-    PYLIBS="PKG_LIBS="`$PYBINPATH/python$PYVERSION-config --ldflags`
-    PYCFLAGS="PKG_CFLAGS="`$PYBINPATH/python$PYVERSION-config --cflags`" -D $PYXY -D PYTHON_IN_R_NO_EXPLICIT_LINKING"
+    PYXY="PYTHONLIBXY=libpython"$PYVERSION"m.so"    
 else 
     echo "python version is < 3"
     PYXY="PYTHONLIBXY=libpython"$PYVERSION".so"
-    PYLIBS="PKG_LIBS="`$PYBINPATH/python$PYVERSION-config --ldflags`
-    PYCFLAGS="PKG_CFLAGS="`$PYBINPATH/python$PYVERSION-config --cflags`" -D $PYXY -D PYTHON_IN_R_NO_EXPLICIT_LINKING"
+fi
+
+if [ $(command -v pkg-config) ]; then
+  PYLIBS="PKG_LIBS="`pkg-config --libs python`
+  PYCFLAGS="PKG_CFLAGS="`pkg-config --cflags --silence-errors python`" -D $PYXY -D PYTHON_IN_R_NO_EXPLICIT_LINKING"
+else 
+  PYLIBS="PKG_LIBS="`$PYBINPATH/python$PYVERSION-config --ldflags`
+  PYCFLAGS="PKG_CFLAGS="`$PYBINPATH/python$PYVERSION-config --cflags`" -D $PYXY -D PYTHON_IN_R_NO_EXPLICIT_LINKING"
 fi
 
 ## echo ""
@@ -55,10 +62,35 @@ fi
 ## echo ""
 
 # replacing Wstric-prototypes removes some unnecessary warnings
-echo $PYLIBS > src/Makevars
-if [ -z "$PICFLAGS" ]; then
-	echo $PYCFLAGS | sed 's/Wstrict-prototypes/pedantic/' | sed 's/ -fstack-protector-strong//' | sed 's/ -Wdate-time//' | sed 's/ -Werror=format-security//' | sed 's/ -Wformat//' >> src/Makevars	
-else 
-	echo $PYCFLAGS | sed 's/Wstrict-prototypes/pedantic/' | sed 's/ -fstack-protector-strong//' | sed 's/ -Wdate-time//' | sed 's/ -Werror=format-security//' | sed 's/ -Wformat//' | sed 's/ -fpic//' >> src/Makevars	
-fi
 
+PYCFLAGS=$(echo $PYCFLAGS | sed 's/ -Wstrict-prototypes//')
+PYCFLAGS=$(echo $PYCFLAGS | sed 's/ -fstack-protector-strong//')
+PYCFLAGS=$(echo $PYCFLAGS | sed 's/ -Wdate-time//')
+PYCFLAGS=$(echo $PYCFLAGS | sed 's/ -Werror=format-security//')
+PYCFLAGS=$(echo $PYCFLAGS | sed 's/ -Wformat//')
+
+## added 27.07.2018
+PYCFLAGS=$(echo $PYCFLAGS | sed 's/ -fstack-clash-protection//')
+PYCFLAGS=$(echo $PYCFLAGS | sed 's/ -fcf-protection//')
+
+if ! [ -z "$PICFLAGS" ]; then
+  PYCFLAGS=$(echo $PYCFLAGS | sed 's/ -fpic//')
+fi 
+
+# if [ -z "$PICFLAGS" ]; then
+#   echo $PYCFLAGS | sed 's/Wstrict-prototypes/pedantic/' | sed 's/ -fstack-protector-strong//' | sed 's/ -Wdate-time//' | sed 's/ -Werror=format-security//' | sed 's/ -Wformat//' >> src/Makevars 
+# else 
+#   echo $PYCFLAGS | sed 's/Wstrict-prototypes/pedantic/' | sed 's/ -fstack-protector-strong//' | sed 's/ -Wdate-time//' | sed 's/ -Werror=format-security//' | sed 's/ -Wformat//' | sed 's/ -fpic//' >> src/Makevars  
+# fi
+
+echo ""
+echo "  Makevars:"
+echo ""
+echo "    "$PYLIBS
+echo ""
+echo "    "$PYCFLAGS
+echo ""
+echo ""
+
+echo ${PYLIBS} > src/Makevars
+echo ${PYCFLAGS} >> src/Makevars
